// carlito | DiPlay property client; vehicle implementation is in a separate GD bridge APK.
plugins { id("com.android.library") }

android {
    namespace = "com.shilapi.xcertplay.vehicleprobe"
    compileSdk = 37
    // carlito | Use the Java contract generated by GD; Windows aidl cannot write to UNC paths.
    // The matching .aidl remains the protocol source alongside this client.
    buildFeatures { aidl = false }
    defaultConfig {
        minSdk = 22
        consumerProguardFiles("consumer-rules.pro")
    }
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies { coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5") }
